---
- name: Reset Blockfile.lock
  command: git checkout Blockfile.lock
- name: Get ssh-agent status
  command: ssh-add -l
- name: Updating ubuntu block
  command: git pull
- name: Sync dependencies
  shell : make sync
- name: Build dependencies
  shell: block bootstrap
- name: Generate .bashrc.cache
  shell : make cache
