---
- name: Reset Blockfile.json.lock
  command: git checkout Blockfile.json.lock
- name: Updating ubuntu block
  command: git pull
- name: Sync dependencies
  shell : make sync
- name: Build dependencies
  shell: block bootstrap
- name: Generate .bashrc.cache
  shell : make cache
